"""
Database module for PostgreSQL connection and operations.

Uses DATABASE_URL environment variable (provided by Coolify).
Implements normalized schema for personal injury litigation practice.

This file is maintained for backwards compatibility. All database functionality
has been refactored into the db/ package. This file re-exports everything from
that package so existing imports continue to work.
"""

# Re-export everything from the db package
from db import *

# Also import the db module itself for attribute access
from db import (
    ValidationError,
    CASE_STATUSES,
    TASK_STATUSES,
    ACTIVITY_TYPES,
    DEFAULT_PERSON_TYPES,
    PERSON_SIDES,
    DEFAULT_EXPERTISE_TYPES,
    DEFAULT_JURISDICTIONS,
    validate_case_status,
    validate_task_status,
    validate_urgency,
    validate_date_format,
    validate_time_format,
    validate_person_type,
    validate_person_side,
    DATABASE_URL,
    _NOT_PROVIDED,
    serialize_value,
    serialize_row,
    serialize_rows,
    get_connection,
    get_cursor,
    drop_all_tables,
    migrate_db,
    init_db,
    seed_jurisdictions,
    seed_expertise_types,
    seed_person_types,
    seed_db,
    get_jurisdictions,
    get_jurisdiction_by_id,
    get_jurisdiction_by_name,
    create_jurisdiction,
    update_jurisdiction,
    delete_jurisdiction,
    get_all_cases,
    get_case_by_id,
    get_case_by_name,
    get_case_summary,
    get_all_case_names,
    create_case,
    update_case,
    delete_case,
    search_cases,
    get_dashboard_stats,
    create_person,
    get_person_by_id,
    update_person,
    search_persons,
    archive_person,
    delete_person,
    assign_person_to_case,
    update_case_assignment,
    remove_person_from_case,
    get_case_persons,
    add_task,
    get_tasks,
    update_task,
    update_task_full,
    delete_task,
    bulk_update_tasks,
    bulk_update_tasks_for_case,
    search_tasks,
    reorder_task,
    add_event,
    get_upcoming_events,
    get_events,
    update_event,
    update_event_full,
    delete_event,
    search_events,
    get_calendar,
    add_activity,
    get_all_activities,
    get_activities,
    update_activity,
    delete_activity,
    add_note,
    update_note,
    delete_note,
    get_notes,
    get_expertise_types,
    create_expertise_type,
    get_expertise_type_by_id,
    update_expertise_type,
    delete_expertise_type,
    get_person_types,
    create_person_type,
    get_person_type_by_id,
    update_person_type,
    delete_person_type,
)
