"""add local_path to sms_message_media

Revision ID: 0260ce9abaad
Revises: a4f2a46619c6
Create Date: 2026-03-04 17:17:24.947926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0260ce9abaad'
down_revision: Union[str, Sequence[str], None] = 'a4f2a46619c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sms_message_media', sa.Column('local_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sms_message_media', 'local_path')
    # ### end Alembic commands ###
