"""add claim/complaint filing dates + complaint deadline note to cases

Revision ID: 1c916f478d79
Revises: 1ecd317aa2ea
Create Date: 2026-06-19 14:14:28.552359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c916f478d79'
down_revision: Union[str, Sequence[str], None] = '1ecd317aa2ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cases', sa.Column('complaint_deadline_note', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('claim_filed_date', sa.Date(), nullable=True))
    op.add_column('cases', sa.Column('claim_rejection_date', sa.Date(), nullable=True))
    op.add_column('cases', sa.Column('complaint_filed_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'complaint_filed_date')
    op.drop_column('cases', 'claim_rejection_date')
    op.drop_column('cases', 'claim_filed_date')
    op.drop_column('cases', 'complaint_deadline_note')
    # ### end Alembic commands ###
