"""add on_trial_calendar to events

Revision ID: 1ecd317aa2ea
Revises: f7a1c9e4d2b8
Create Date: 2026-06-18 15:31:21.926583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ecd317aa2ea'
down_revision: Union[str, Sequence[str], None] = 'f7a1c9e4d2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('on_trial_calendar', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'on_trial_calendar')
    # ### end Alembic commands ###
