"""add notes column to events

Revision ID: 1fafb4a8ba5e
Revises: c1ac1736501b
Create Date: 2026-05-23 17:37:22.633421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fafb4a8ba5e'
down_revision: Union[str, Sequence[str], None] = 'c1ac1736501b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'notes')
    # ### end Alembic commands ###
