"""add worklog tables

Revision ID: 2b98d72ee01b
Revises: 1c916f478d79
Create Date: 2026-06-23 12:09:39.536154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b98d72ee01b'
down_revision: Union[str, Sequence[str], None] = '1c916f478d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('transcript', sa.Text(), nullable=True),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'processing'"), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name='voice_logs_created_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='voice_logs_pkey')
    )
    op.create_index('idx_voice_logs_log_date', 'voice_logs', ['log_date'], unique=False)
    op.create_index('idx_voice_logs_status', 'voice_logs', ['status'], unique=False)
    op.create_table('worklog_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voice_log_id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('raw_reference', sa.Text(), nullable=True),
    sa.Column('activity_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name='worklog_entries_case_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['voice_log_id'], ['voice_logs.id'], name='worklog_entries_voice_log_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='worklog_entries_pkey')
    )
    op.create_index('idx_worklog_entries_activity_date', 'worklog_entries', ['activity_date'], unique=False)
    op.create_index('idx_worklog_entries_case_id', 'worklog_entries', ['case_id'], unique=False)
    op.create_index('idx_worklog_entries_voice_log_id', 'worklog_entries', ['voice_log_id'], unique=False)
    op.create_table('worklog_entry_people',
    sa.Column('entry_id', sa.Integer(), nullable=False),
    sa.Column('person_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['entry_id'], ['worklog_entries.id'], name='worklog_entry_people_entry_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name='worklog_entry_people_person_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id', 'person_id', name='worklog_entry_people_pkey')
    )
    op.create_index('idx_worklog_entry_people_person_id', 'worklog_entry_people', ['person_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_worklog_entry_people_person_id', table_name='worklog_entry_people')
    op.drop_table('worklog_entry_people')
    op.drop_index('idx_worklog_entries_voice_log_id', table_name='worklog_entries')
    op.drop_index('idx_worklog_entries_case_id', table_name='worklog_entries')
    op.drop_index('idx_worklog_entries_activity_date', table_name='worklog_entries')
    op.drop_table('worklog_entries')
    op.drop_index('idx_voice_logs_status', table_name='voice_logs')
    op.drop_index('idx_voice_logs_log_date', table_name='voice_logs')
    op.drop_table('voice_logs')
    # ### end Alembic commands ###
