"""add case_comments and case_comment_reads tables

Revision ID: 2cea46dbbb57
Revises: b860e31f39c6
Create Date: 2026-02-23 14:52:17.035728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2cea46dbbb57'
down_revision: Union[str, Sequence[str], None] = 'b860e31f39c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_comment_reads',
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name='case_comment_reads_case_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='case_comment_reads_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('case_id', 'user_id', name='case_comment_reads_pkey')
    )
    op.create_table('case_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('detail', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name='case_comments_case_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='case_comments_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='case_comments_pkey')
    )
    op.create_index('idx_case_comments_case_id', 'case_comments', ['case_id'], unique=False)
    op.create_index('idx_case_comments_user_id', 'case_comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_case_comments_user_id', table_name='case_comments')
    op.drop_index('idx_case_comments_case_id', table_name='case_comments')
    op.drop_table('case_comments')
    op.drop_table('case_comment_reads')
    # ### end Alembic commands ###
