"""add objections table

Revision ID: 45b7e722cbb7
Revises: 0c4e6a5649ff
Create Date: 2026-02-12 16:53:17.679955

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45b7e722cbb7'
down_revision: Union[str, Sequence[str], None] = '0c4e6a5649ff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('objections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('formal_language', sa.Text(), nullable=False),
    sa.Column('argument_template', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='objections_pkey'),
    sa.UniqueConstraint('short_name', name='objections_short_name_key')
    )
    op.create_index('idx_objections_position', 'objections', ['position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_objections_position', table_name='objections')
    op.drop_table('objections')
    # ### end Alembic commands ###
