"""add is_system flag to roles

Revision ID: 4c2e001750ee
Revises: bfe098508d1f
Create Date: 2026-05-24 10:52:05.158454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c2e001750ee'
down_revision: Union[str, Sequence[str], None] = 'bfe098508d1f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


SYSTEM_ROLE_NAMES = [
    "plaintiff", "contact", "guardian_ad_litem", "decedent",
    "co_counsel", "referring_attorney", "opposing_counsel",
    "criminal_defense_attorney", "prosecutor", "public_defender",
    "municipality_defendant", "individual_defendant",
    "plaintiff_expert", "defense_expert",
    "mediator",
    "lien_holder", "witness", "claims_adjuster", "special_needs_consultant",
]


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###

    # Mark existing seeded roles as system roles
    roles_table = sa.table('roles', sa.column('name', sa.String), sa.column('is_system', sa.Boolean))
    op.execute(
        roles_table.update()
        .where(roles_table.c.name.in_(SYSTEM_ROLE_NAMES))
        .values(is_system=True)
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_system')
    # ### end Alembic commands ###
