"""worklog editable ledger: entry created_by, nullable voice_log, sources

Revision ID: 4cd38a4981c3
Revises: 2b98d72ee01b
Create Date: 2026-06-24 09:02:01.246238

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4cd38a4981c3'
down_revision: Union[str, Sequence[str], None] = '2b98d72ee01b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_log_sources',
    sa.Column('voice_log_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['voice_log_id'], ['voice_logs.id'], name='voice_log_sources_voice_log_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('voice_log_id', 'source_type', 'source_id', name='voice_log_sources_pkey')
    )
    op.add_column('worklog_entries', sa.Column('created_by', sa.Integer(), nullable=True))
    op.alter_column('worklog_entries', 'voice_log_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index('idx_worklog_entries_author_date', 'worklog_entries', ['created_by', 'activity_date'], unique=False)
    op.create_foreign_key('worklog_entries_created_by_fkey', 'worklog_entries', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

    # Data migrations: backfill entry authorship from the parent log, and
    # collapse the old review statuses into the new single 'done' state.
    op.execute(
        "UPDATE worklog_entries we SET created_by = vl.created_by "
        "FROM voice_logs vl WHERE we.voice_log_id = vl.id AND we.created_by IS NULL"
    )
    op.execute("UPDATE voice_logs SET status = 'done' WHERE status IN ('ready', 'confirmed')")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('worklog_entries_created_by_fkey', 'worklog_entries', type_='foreignkey')
    op.drop_index('idx_worklog_entries_author_date', table_name='worklog_entries')
    op.alter_column('worklog_entries', 'voice_log_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('worklog_entries', 'created_by')
    op.drop_table('voice_log_sources')
    # ### end Alembic commands ###
