"""add case_financials and case_counsel_fees tables

Revision ID: 5748aa2a68ad
Revises: e82adeae6bce
Create Date: 2026-04-12 11:07:51.676941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5748aa2a68ad'
down_revision: Union[str, Sequence[str], None] = 'e82adeae6bce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_financials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('resolution_type', sa.String(length=50), nullable=True),
    sa.Column('resolution_date', sa.Date(), nullable=True),
    sa.Column('gross_recovery', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('costs_advanced', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('liens_total', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('is_finalized', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name='case_financials_case_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='case_financials_pkey'),
    sa.UniqueConstraint('case_id', name='case_financials_case_id_key')
    )
    op.create_index('idx_case_financials_case_id', 'case_financials', ['case_id'], unique=False)
    op.create_index('idx_case_financials_resolution_type', 'case_financials', ['resolution_type'], unique=False)
    op.create_table('case_counsel_fees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('financial_id', sa.Integer(), nullable=False),
    sa.Column('person_role_id', sa.Integer(), nullable=True),
    sa.Column('counsel_name', sa.String(length=255), nullable=True),
    sa.Column('is_our_firm', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('fee_type', sa.String(length=20), server_default=sa.text("'percentage'::character varying"), nullable=True),
    sa.Column('fee_percentage', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fee_flat_amount', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['financial_id'], ['case_financials.id'], name='case_counsel_fees_financial_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['person_role_id'], ['person_roles.id'], name='case_counsel_fees_person_role_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='case_counsel_fees_pkey')
    )
    op.create_index('idx_case_counsel_fees_financial_id', 'case_counsel_fees', ['financial_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_case_counsel_fees_financial_id', table_name='case_counsel_fees')
    op.drop_table('case_counsel_fees')
    op.drop_index('idx_case_financials_resolution_type', table_name='case_financials')
    op.drop_index('idx_case_financials_case_id', table_name='case_financials')
    op.drop_table('case_financials')
    # ### end Alembic commands ###
