"""add ai columns to intakes

Revision ID: 59ad1bfcf908
Revises: 0d2826b6dcb9
Create Date: 2026-02-19 14:15:32.144503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59ad1bfcf908'
down_revision: Union[str, Sequence[str], None] = '0d2826b6dcb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intakes', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('intakes', sa.Column('ai_rating', sa.Integer(), nullable=True))
    op.add_column('intakes', sa.Column('ai_rating_reasoning', sa.Text(), nullable=True))


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('intakes', 'ai_rating_reasoning')
    op.drop_column('intakes', 'ai_rating')
    op.drop_column('intakes', 'ai_summary')
    # ### end Alembic commands ###
