"""add intake_comments and intake_comment_reads

Revision ID: 937ce83ccc7c
Revises: 59ad1bfcf908
Create Date: 2026-02-19 15:55:43.636831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '937ce83ccc7c'
down_revision: Union[str, Sequence[str], None] = '59ad1bfcf908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intake_comment_reads',
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], name='intake_comment_reads_intake_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='intake_comment_reads_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('intake_id', 'user_id', name='intake_comment_reads_pkey')
    )
    op.create_table('intake_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intake_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['intake_id'], ['intakes.id'], name='intake_comments_intake_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='intake_comments_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='intake_comments_pkey')
    )
    op.create_index('idx_intake_comments_intake_id', 'intake_comments', ['intake_id'], unique=False)
    op.create_index('idx_intake_comments_user_id', 'intake_comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_intake_comments_user_id', table_name='intake_comments')
    op.drop_index('idx_intake_comments_intake_id', table_name='intake_comments')
    op.drop_table('intake_comments')
    op.drop_table('intake_comment_reads')
    # ### end Alembic commands ###
