"""add sms_conversations and sms_messages tables

Revision ID: 9381a086f938
Revises: 4a695b9ae955
Create Date: 2026-02-26 16:45:32.846914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9381a086f938'
down_revision: Union[str, Sequence[str], None] = '4a695b9ae955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_conversations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('label', sa.Text(), nullable=True),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='sms_conversations_pkey'),
    sa.UniqueConstraint('phone_number', name='sms_conversations_phone_number_key')
    )
    op.create_index('idx_sms_conversations_last_message_at', 'sms_conversations', ['last_message_at'], unique=False)
    op.create_index('idx_sms_conversations_phone_number', 'sms_conversations', ['phone_number'], unique=False)
    op.create_table('sms_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('sent_by_user_id', sa.Integer(), nullable=True),
    sa.Column('twilio_sid', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'sent'::character varying"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['sms_conversations.id'], name='sms_messages_conversation_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], name='sms_messages_sent_by_user_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='sms_messages_pkey')
    )
    op.create_index('idx_sms_messages_conversation_id', 'sms_messages', ['conversation_id'], unique=False)
    op.create_index('idx_sms_messages_created_at', 'sms_messages', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sms_messages_created_at', table_name='sms_messages')
    op.drop_index('idx_sms_messages_conversation_id', table_name='sms_messages')
    op.drop_table('sms_messages')
    op.drop_index('idx_sms_conversations_phone_number', table_name='sms_conversations')
    op.drop_index('idx_sms_conversations_last_message_at', table_name='sms_conversations')
    op.drop_table('sms_conversations')
    # ### end Alembic commands ###
