"""add location_short to intakes

Revision ID: a08dfc58f2e5
Revises: 649a2fe6872e
Create Date: 2026-02-22 21:30:55.690837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a08dfc58f2e5'
down_revision: Union[str, Sequence[str], None] = '649a2fe6872e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intakes', sa.Column('location_short', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intakes', 'location_short')
    # ### end Alembic commands ###
