"""add sms archive and media support

Revision ID: a4f2a46619c6
Revises: 9381a086f938
Create Date: 2026-03-04 12:22:55.226978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4f2a46619c6'
down_revision: Union[str, Sequence[str], None] = '9381a086f938'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_message_media',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('original_url', sa.Text(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['sms_messages.id'], name='sms_message_media_message_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='sms_message_media_pkey')
    )
    op.create_index('idx_sms_message_media_message_id', 'sms_message_media', ['message_id'], unique=False)
    op.add_column('sms_conversations', sa.Column('archived', sa.Boolean(), server_default=sa.text('false'), nullable=True))
    op.create_index('idx_sms_conversations_archived', 'sms_conversations', ['archived'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sms_conversations_archived', table_name='sms_conversations')
    op.drop_column('sms_conversations', 'archived')
    op.drop_index('idx_sms_message_media_message_id', table_name='sms_message_media')
    op.drop_table('sms_message_media')
    # ### end Alembic commands ###
