"""move intake link to intakes.case_id (multiple intakes per case)

Revision ID: a7e888b89d84
Revises: d2cd156b344a
Create Date: 2026-05-28 08:05:35.312592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7e888b89d84'
down_revision: Union[str, Sequence[str], None] = 'd2cd156b344a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('cases_intake_id_fkey'), 'cases', type_='foreignkey')
    op.drop_column('cases', 'intake_id')
    op.add_column('intakes', sa.Column('case_id', sa.Integer(), nullable=True))
    op.create_index('idx_intakes_case_id', 'intakes', ['case_id'], unique=False)
    op.create_foreign_key('intakes_case_id_fkey', 'intakes', 'cases', ['case_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('intakes_case_id_fkey', 'intakes', type_='foreignkey')
    op.drop_index('idx_intakes_case_id', table_name='intakes')
    op.drop_column('intakes', 'case_id')
    op.add_column('cases', sa.Column('intake_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('cases_intake_id_fkey'), 'cases', 'intakes', ['intake_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###
