"""add detail jsonb to intake_comments

Revision ID: b860e31f39c6
Revises: a08dfc58f2e5
Create Date: 2026-02-22 22:24:35.132256

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b860e31f39c6'
down_revision: Union[str, Sequence[str], None] = 'a08dfc58f2e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('intake_comments', sa.Column('detail', postgresql.JSONB(none_as_null=True, astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('intake_comments', 'detail')
    # ### end Alembic commands ###
