"""add intakes table

Revision ID: cd803e398ff9
Revises: b0ccd4398a17
Create Date: 2026-02-19 12:51:36.772365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd803e398ff9'
down_revision: Union[str, Sequence[str], None] = 'b0ccd4398a17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intakes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submitted_on', sa.DateTime(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=100), nullable=True),
    sa.Column('case_type', sa.String(length=255), nullable=True),
    sa.Column('incident_date', sa.Date(), nullable=True),
    sa.Column('incident_time', sa.String(length=50), nullable=True),
    sa.Column('location', sa.Text(), nullable=True),
    sa.Column('incident_description', sa.Text(), nullable=True),
    sa.Column('injury_description', sa.Text(), nullable=True),
    sa.Column('disclaimer_accepted', sa.Boolean(), server_default=sa.text('false'), nullable=True),
    sa.Column('status', sa.String(length=50), server_default=sa.text("'Reviewing'::character varying"), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('google_row_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id', name='intakes_pkey'),
    sa.UniqueConstraint('google_row_number', name='intakes_google_row_number_key')
    )
    op.create_index('idx_intakes_status', 'intakes', ['status'], unique=False)
    op.create_index('idx_intakes_submitted_on', 'intakes', ['submitted_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_intakes_submitted_on', table_name='intakes')
    op.drop_index('idx_intakes_status', table_name='intakes')
    op.drop_table('intakes')
    # ### end Alembic commands ###
