"""add alert_dismissals table

Revision ID: d2cd156b344a
Revises: b270d6c4ce72
Create Date: 2026-05-26 21:06:09.724070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2cd156b344a'
down_revision: Union[str, Sequence[str], None] = 'b270d6c4ce72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_dismissals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('rule_id', sa.String(length=50), nullable=False),
    sa.Column('fingerprint', sa.Text(), nullable=True),
    sa.Column('dismissed_by', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name='alert_dismissals_case_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['dismissed_by'], ['users.id'], name='alert_dismissals_dismissed_by_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='alert_dismissals_pkey'),
    sa.UniqueConstraint('case_id', 'rule_id', name='uq_alert_dismissals_case_rule')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_dismissals')
    # ### end Alembic commands ###
