"""add twilio_sid index to sms_messages

Revision ID: ded88db86b31
Revises: e295b77673c1
Create Date: 2026-05-22 17:35:38.885476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ded88db86b31'
down_revision: Union[str, Sequence[str], None] = 'e295b77673c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_sms_messages_twilio_sid', 'sms_messages', ['twilio_sid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sms_messages_twilio_sid', table_name='sms_messages')
    # ### end Alembic commands ###
