"""add intake_id to tasks

Revision ID: e295b77673c1
Revises: e845739db79f
Create Date: 2026-05-22 17:08:04.944752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e295b77673c1'
down_revision: Union[str, Sequence[str], None] = 'e845739db79f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('intake_id', sa.Integer(), nullable=True))
    op.create_index('idx_tasks_intake_id', 'tasks', ['intake_id'], unique=False)
    op.create_foreign_key('tasks_intake_id_fkey', 'tasks', 'intakes', ['intake_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('tasks_intake_id_fkey', 'tasks', type_='foreignkey')
    op.drop_index('idx_tasks_intake_id', table_name='tasks')
    op.drop_column('tasks', 'intake_id')
    # ### end Alembic commands ###
