"""add sms_conversation_reads table

Revision ID: e82adeae6bce
Revises: 0260ce9abaad
Create Date: 2026-03-04 17:52:13.505305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e82adeae6bce'
down_revision: Union[str, Sequence[str], None] = '0260ce9abaad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_conversation_reads',
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_read_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['sms_conversations.id'], name='sms_conversation_reads_conversation_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='sms_conversation_reads_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id', name='sms_conversation_reads_pkey')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sms_conversation_reads')
    # ### end Alembic commands ###
