"""drop sms tables

Revision ID: fde1266d3d02
Revises: db2cb98cdc1b
Create Date: 2026-08-24 09:17:55.898652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fde1266d3d02'
down_revision: Union[str, Sequence[str], None] = 'db2cb98cdc1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop children before parents so FK dependencies are satisfied.
    op.drop_index(op.f('idx_sms_message_media_message_id'), table_name='sms_message_media')
    op.drop_table('sms_message_media')
    op.drop_table('sms_conversation_reads')
    op.drop_index(op.f('idx_sms_messages_conversation_id'), table_name='sms_messages')
    op.drop_index(op.f('idx_sms_messages_created_at'), table_name='sms_messages')
    op.drop_index(op.f('idx_sms_messages_twilio_sid'), table_name='sms_messages')
    op.drop_table('sms_messages')
    op.drop_index(op.f('idx_sms_conversations_archived'), table_name='sms_conversations')
    op.drop_index(op.f('idx_sms_conversations_case_id'), table_name='sms_conversations')
    op.drop_index(op.f('idx_sms_conversations_last_message_at'), table_name='sms_conversations')
    op.drop_index(op.f('idx_sms_conversations_person_id'), table_name='sms_conversations')
    op.drop_index(op.f('idx_sms_conversations_phone_number'), table_name='sms_conversations')
    op.drop_table('sms_conversations')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sms_conversations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('label', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('case_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('person_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('last_message_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('archived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('sms_conversations_case_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['person_id'], ['persons.id'], name=op.f('sms_conversations_person_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('sms_conversations_pkey')),
    sa.UniqueConstraint('phone_number', name=op.f('sms_conversations_phone_number_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('idx_sms_conversations_phone_number'), 'sms_conversations', ['phone_number'], unique=False)
    op.create_index(op.f('idx_sms_conversations_person_id'), 'sms_conversations', ['person_id'], unique=False)
    op.create_index(op.f('idx_sms_conversations_last_message_at'), 'sms_conversations', ['last_message_at'], unique=False)
    op.create_index(op.f('idx_sms_conversations_case_id'), 'sms_conversations', ['case_id'], unique=False)
    op.create_index(op.f('idx_sms_conversations_archived'), 'sms_conversations', ['archived'], unique=False)
    op.create_table('sms_messages',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('direction', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('sent_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('twilio_sid', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'sent'::character varying"), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['sms_conversations.id'], name=op.f('sms_messages_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sent_by_user_id'], ['users.id'], name=op.f('sms_messages_sent_by_user_id_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('sms_messages_pkey'))
    )
    op.create_index(op.f('idx_sms_messages_twilio_sid'), 'sms_messages', ['twilio_sid'], unique=False)
    op.create_index(op.f('idx_sms_messages_created_at'), 'sms_messages', ['created_at'], unique=False)
    op.create_index(op.f('idx_sms_messages_conversation_id'), 'sms_messages', ['conversation_id'], unique=False)
    op.create_table('sms_message_media',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('original_url', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('local_path', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('file_size', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['sms_messages.id'], name=op.f('sms_message_media_message_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sms_message_media_pkey'))
    )
    op.create_index(op.f('idx_sms_message_media_message_id'), 'sms_message_media', ['message_id'], unique=False)
    op.create_table('sms_conversation_reads',
    sa.Column('conversation_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('last_read_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['sms_conversations.id'], name=op.f('sms_conversation_reads_conversation_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('sms_conversation_reads_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversation_id', 'user_id', name=op.f('sms_conversation_reads_pkey'))
    )
    # ### end Alembic commands ###
